// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"lineofsight","status":true,"description":"","parameters":{}},
{"name":"DMY_SkipVideo","status":true,"description":"Skip video on key press","parameters":{"Disabler switch":"0"}}
];
