// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"lineofsight","status":true,"description":"","parameters":{}},
{"name":"DMY_SkipVideo","status":true,"description":"Skip video on key press","parameters":{"Disabler switch":"0"}},
{"name":"Galv_VariableBar","status":true,"description":"(v.1.0) A graphical bar that displays in the map scene to show the current value of a max value visually using variables.","parameters":{}},
{"name":"lineofsight2","status":true,"description":"","parameters":{}},
{"name":"YEP_SaveEventLocations","status":true,"description":"v1.06 Enable specified maps to memorize the locations of\nevents when leaving and loading them upon reentering map.","parameters":{}},
{"name":"GALV_VisibilityRange","status":true,"description":"(v.1.2) Use an image to display a visibility range image around the player's position","parameters":{"Zoom Variable":"17","Opacity Variable":"18","Z Position":"10"}}
];
